### ISSUE TITLE
add a default setup option similar to giraffez

### ISSUE THREAD

**Issue by ian-whitestone** [ian-whitestone/postgrez#4]
in the `.postgrez` yaml file, allow users to specify which setup is their default:

```yaml
default: my_db1

my_db1:
    host: XXX
    user: postgres
    password: XXX
    database: XXX
    port: 5432

my_db2:
    host: XXX
    user: postgres
    password: XXX
    database: XXX
    port: 5432
```

Users can then call the functions without specifying a db configuration:

```python
data = [(1, 2, 3), (4, 5, 6)]
postgrez.load(table_name='my_table', data=data)
```
